### PR TITLE
Taiwan is just Taiwan

### PR DESCRIPTION
**Pull request by tristanoneil**
🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼🇹🇼

Apparently this is controversial but they have their own president so I think they deserve to just be Taiwan.

### CODE REVIEW

**Comment by benkeen** [comment]
Fair 'nuff!

**Comment by tristanoneil** [comment]
@benkeen Thanks! So what's the process for this update getting into benkeen/country-region-selector?

**Comment by benkeen** [comment]
I just need to cut a new release of that script. I'll get one out the door tomorrow night. Sorry for the wait!

**Comment by tristanoneil** [comment]
@benkeen No worries, thanks!

**Comment by benkeen** [comment]
Done! Just released 0.3.3 of country-region-selector.

**Comment by tristanoneil** [comment]
@benkeen awesome thanks. Do you need to create a new tag as well? I'm getting the following error when upgrading via bower.

`Available versions in https://github.com/benkeen/country-region-selector.git: 0.3.2, 0.3.1, 0.3.0, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.9, 0.1.8, 0.1.7, 0.1.3, 0.1.2, 0.1.1`

**Comment by benkeen** [comment]
Done!

**Comment by tristanoneil** [comment]
Thanks!

**Pull request merged**
