### PR TITLE
Patch 1 - update of Russian regions 

### PR DESCRIPTION
**Pull request by korshunad**
Added some missing Russian Regions - Penza Oblast, Kaliningrad Oblast, Kemerovo Oblast, 
Removed Permskaya (it's Perm Krai now)
Renamed all the Russian Regions names according to wiki (https://en.wikipedia.org/wiki/Federal_subjects_of_Russia)

### CODE REVIEW

**Comment by benkeen** [comment]
Nice, thanks @korshunad! I see it's currently red: would you mind running `grunt validate` locally to locate the syntax error in your change and recommit?

**Comment by korshunad** [comment]
Hi, @benkeen ! error fixed and change recommited :)

**Comment by benkeen** [comment]
Brilliant, thanks @korshunad! Merged. I'll release an update to the script today or tomorrow.

**Comment by korshunad** [comment]
Thank you for the great library! Glad to help :)

**Pull request merged**
