### PR TITLE
Update region for france

### PR DESCRIPTION
**Pull request by JMartelot**
Update new region in JSON file.

### CODE REVIEW

**Comment by benkeen** [comment]
Cool, thanks @JMartelot - do you have a link anywhere that documents that these are the correct regions in France? That would help me determine if it's all okay (I'm sure it is!).

**Comment by JMartelot** [comment]
Yeah of course ! You can find new region with code here : https://fr.wikipedia.org/wiki/Codes_g%C3%A9ographiques_de_la_France

And here an official link : http://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Les-noms-des-nouvelles-regions-sont-actes

In french of course ;)

**Comment by benkeen** [comment]
Great stuff, thanks @JMartelot! I'll do an new release now.

**Comment by JMartelot** [comment]
@benkeen you welcome! Thanks for the release.

**Pull request merged**
